use actix_web::{App, Error, HttpServer, Responder, get, web::{self}};
use serde::Serialize;
use serde_json::Value;
use sqlite;


#[derive(Serialize)]
struct Data{
    name: String,
    data: Value
}

#[derive(Serialize)]
struct Healthy{
    health: String
}

#[get("/")]
async fn health() -> Result<impl Responder, Error> {
    let health = Healthy {
        health: "Ok".to_string()
    };
    Ok(web::Json(health))
}

#[get("/{name}")]
async fn index(name: web::Path<String>) -> Result<impl Responder, Error> {
    let connection   = sqlite::open("pf.db").unwrap();
    let exe = connection.execute("
    CREATE TABLE IF NOT EXISTS world(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    data JSONB);
    INSERT INTO world('test', '{'test':'test'}')
    ").unwrap();
    print!("{:?}, {}", exe, name);
    Ok("Ok")
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    
    HttpServer::new(|| App::new().service(index).service(health))
        .bind(("127.0.0.1", 3000))?
        .run()
        .await
}